driver:
 name: docker
 binary: docker
 use_sudo: false

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.3.0-1

platforms:
- name: centos-6.6
- name: centos-7.2
  driver_config:
    image: centos:centos7
    run_command: /usr/sbin/init
    privileged: true

suites:
  - name: default
    run_list:
       - recipe[test_tuned::create_apply_profile]
    attributes:
  - name: provider
    run_list:
       - recipe[test_tuned::create_provider_apply_profile]
    attributes:
