driver:
 name: docker
 binary: docker
 use_sudo: false

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.3.0-1

platforms:
- name: centos-6.6
- name: centos-7.1
  driver_config:
    #image: centos:centos7
    dockerfile: test/Dockerfile
    #run_command: /usr/sbin/init
    privileged: true

suites:
  - name: default
    run_list:
       - recipe[test_tuned::create_apply_profile]
    attributes:
    