driver:
 name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: "data_bags"
  roles_path: "roles"
  environments_path: "environments"
  require_chef_omnibus: true

platforms:
- name: centos-6.6
- name: centos-7.0

suites:
  - name: default
    run_list:
       - recipe[test_tuned::create_apply_profile]
    attributes:
