driver:
 name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
- name: centos-6.6
- name: centos-7.1

suites:
  - name: default
    run_list:
       - recipe[test_tuned::create_apply_profile]
    attributes:
