language: ruby
cache: bundler
rvm:
- 2.1.5
sudo: required
services:
  - docker
before_install:
- curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -v 12.0.3

script:
- chef exec foodcritic -f any .
- chef exec rubocop
- chef exec rspec
- chef exec kitchen test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/85ee0437f8b6a788fa87
    on_success: change
    on_failure: always
    on_start: never
